apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: domain-check
  namespace: domain-check
  labels:
    app.kubernetes.io/name: domain-check
    app.kubernetes.io/component: monitoring
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: domain-check
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
