#!/bin/bash
# Configure git settings for automatic garbage collection
# This script sets up git to automatically run garbage collection
# when the number of loose objects exceeds the threshold

set -euo pipefail

echo "Configuring git automatic garbage collection settings..."

# Configure automatic GC settings
# git gc --auto runs when the number of loose objects exceeds gc.auto
git config --local gc.auto 256
echo "✅ Set gc.auto = 256 (runs auto GC when >256 loose objects)"

# Limit the number of packs generated by auto GC
git config --local gc.autoPackLimit 10
echo "✅ Set gc.autoPackLimit = 10 (limits packs in auto GC)"

# Configure aggressive GC depth for better compression
git config --local gc.aggressiveDepth 50
echo "✅ Set gc.aggressiveDepth = 50 (better compression)"

# Prune loose objects older than 2 weeks
git config --local gc.pruneExpire "2.weeks.ago"
echo "✅ Set gc.pruneExpire = 2.weeks.ago"

# Keep reflogs for 90 days
git config --local gc.reflogExpire "90 days"
echo "✅ Set gc.reflogExpire = 90 days"

# Keep unreachable reflogs for 30 days
git config --local gc.reflogExpireUnreachable "30 days"
echo "✅ Set gc.reflogExpireUnreachable = 30 days"

# Enable pack refs
git config --local gc.packRefs true
echo "✅ Set gc.packRefs = true"

echo ""
echo "✅ Git GC configuration complete!"
echo ""
echo "Current git GC settings:"
git config --local --get-regexp "^gc\."
